// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Task struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	ProjectTag    string     `json:"project_tag"`
	Priority      string     `json:"priority"`
	Deadline      *time.Time `json:"deadline"`
	RawTranscript *string    `json:"raw_transcript"`
	Completed     bool       `json:"completed"`
	CompletedAt   *time.Time `json:"completed_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	SortOrder     int32      `json:"sort_order"`
}

type TimeEntry struct {
	ID            string     `json:"id"`
	Matter        string     `json:"matter"`
	Description   string     `json:"description"`
	RawTranscript *string    `json:"raw_transcript"`
	StartTime     time.Time  `json:"start_time"`
	EndTime       *time.Time `json:"end_time"`
	DurationSecs  int        `json:"duration_secs"`
	BillableHours float64    `json:"billable_hours"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}
