// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Task struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	ProjectTag    string     `json:"project_tag"`
	Priority      string     `json:"priority"`
	Deadline      *time.Time `json:"deadline"`
	RawTranscript *string    `json:"raw_transcript"`
	Completed     bool       `json:"completed"`
	CompletedAt   *time.Time `json:"completed_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	SortOrder     int32      `json:"sort_order"`
}
