// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const clearCompleted = `-- name: ClearCompleted :execrows
DELETE FROM tasks WHERE completed = TRUE
`

func (q *Queries) ClearCompleted(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, clearCompleted)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (title, project_tag, priority, deadline, raw_transcript)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, project_tag, priority, deadline, raw_transcript,
          completed, completed_at, created_at, updated_at, sort_order
`

type InsertTaskParams struct {
	Title         string     `json:"title"`
	ProjectTag    string     `json:"project_tag"`
	Priority      string     `json:"priority"`
	Deadline      *time.Time `json:"deadline"`
	RawTranscript *string    `json:"raw_transcript"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.Title,
		arg.ProjectTag,
		arg.Priority,
		arg.Deadline,
		arg.RawTranscript,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProjectTag,
		&i.Priority,
		&i.Deadline,
		&i.RawTranscript,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, project_tag, priority, deadline, raw_transcript,
       completed, completed_at, created_at, updated_at, sort_order
FROM tasks
ORDER BY
  project_tag ASC,
  completed ASC,
  CASE priority
    WHEN 'urgent' THEN 0
    WHEN 'high'   THEN 1
    WHEN 'normal' THEN 2
    WHEN 'low'    THEN 3
  END ASC,
  sort_order ASC,
  created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectTag,
			&i.Priority,
			&i.Deadline,
			&i.RawTranscript,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTask = `-- name: ToggleTask :one
UPDATE tasks
SET completed = NOT completed,
    completed_at = CASE WHEN NOT completed THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, project_tag, priority, deadline, raw_transcript,
          completed, completed_at, created_at, updated_at, sort_order
`

func (q *Queries) ToggleTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, toggleTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProjectTag,
		&i.Priority,
		&i.Deadline,
		&i.RawTranscript,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}

const updateSortOrder = `-- name: UpdateSortOrder :execrows
UPDATE tasks SET sort_order = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSortOrderParams struct {
	ID        string `json:"id"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpdateSortOrder(ctx context.Context, arg UpdateSortOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSortOrder, arg.ID, arg.SortOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE(NULLIF($1::text, ''), title),
    project_tag = COALESCE(NULLIF($2::text, ''), project_tag),
    priority = COALESCE(NULLIF($3::text, ''), priority),
    deadline = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, title, project_tag, priority, deadline, raw_transcript,
          completed, completed_at, created_at, updated_at, sort_order
`

type UpdateTaskParams struct {
	Title      string     `json:"title"`
	ProjectTag string     `json:"project_tag"`
	Priority   string     `json:"priority"`
	Deadline   *time.Time `json:"deadline"`
	ID         string     `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.ProjectTag,
		arg.Priority,
		arg.Deadline,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProjectTag,
		&i.Priority,
		&i.Deadline,
		&i.RawTranscript,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortOrder,
	)
	return i, err
}
